name: "Generate new release"

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest
    env:
      working-directory: ./LearningMachine
      build-directory: ./LearningMachine/app/build/outputs/apk

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          java-package: jdk
          architecture: x64

      - name: Java Version
        run: java -version

      - name: Copy package Debug Keystore to runner
        run: |
          mkdir -p /home/runner/.android
          cp ./keys/debug.keystore /home/runner/.android

      - name: Generate Development *.apk
        run: ./gradlew assembleDev
        working-directory: ${{ env.working-directory }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Generate Production *.apk
        run: ./gradlew assembleProduction
        working-directory: ${{ env.working-directory }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Development Debug Asset
        id: upload-dev-debug-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.build-directory }}/dev/debug/certifico-devDebug-${{ steps.get_version.outputs.version }}-debug.apk
          asset_name: certifico-devDebug-${{ steps.get_version.outputs.version }}-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset 
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.build-directory }}/production/release/certifico-productionRelease-${{ steps.get_version.outputs.version }}.apk
          asset_name: certifico-productionRelease-${{ steps.get_version.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Debug Asset 
        id: upload-debug-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.build-directory }}/production/debug/certifico-productionDebug-${{ steps.get_version.outputs.version }}-debug.apk
          asset_name: certifico-productionDebug-${{ steps.get_version.outputs.version }}-debug.apk
          asset_content_type: application/vnd.android.package-archive
